    -- local multiplayer = {}
    -- local j = 172
    -- if true then -- @TODO: check for ongoing tournament
    --     table.insert(multiplayer, Button.new({
    --         position = {344, j},
    --         size     = {128, 32},
    --         text     = T"Continue Tournament",
    --     }))
    --     j = j + 64
    -- end
    -- table.insert(multiplayer, Button.new({
    --     position = {344, j},
    --     size     = {128, 32},
    --     text     = T"New Tournament",
    -- }))
    -- j = j + 64
    -- table.insert(multiplayer, Button.new({
    --     position = {344, j},
    --     size     = {128, 32},
    --     text     = T"New Friendly",
    -- }))
    -- j = j + 64
    -- table.insert(multiplayer, Button.new({
    --     position = {344, j},
    --     size     = {128, 32},
    --     text     = T"Profile",
    -- }))
    -- j = j + 64
    -- table.insert(multiplayer, Button.new({
    --     position = {344, j},
    --     size     = {128, 32},
    --     text     = T"Back",
    --     onclick  = function()
    --         gui_manager.switchTo('title')
    --     end
    -- }))
    -- j = j + 64
    -- gui_manager.register('multiplayer', multiplayer)
